# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=391904c0f233618bdeb653c44cb300102a64fb530505ac7c489ce9265f8869b2
language: node_js
cache:
  directories:
    - "node_modules"
node_js:
  - "stable"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
install:
  - npm install 
script:
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
